/**
 * Vector DB Type Definitions
 */

import { z } from 'zod';

/**
 * 13-dimensional product tensor for SKA analysis
 * Derived from 13 semantic atoms
 */
export const ProductTensorSchema = z.object({
  productId: z.string().uuid(),
  vector: z.array(z.number()).length(13),
  generatedAt: z.date(),
  metadata: z
    .object({
      sku: z.string().optional(),
      brand: z.string().optional(),
      category: z.string().optional(),
    })
    .optional(),
});

export type ProductTensor = z.infer<typeof ProductTensorSchema>;

/**
 * 792-dimensional semantic embedding for NLP search
 * Generated by text-embedding-3-small
 */
export const ProductEmbeddingSchema = z.object({
  productId: z.string().uuid(),
  vector: z.array(z.number()).length(792),
  generatedAt: z.date(),
  textSource: z.enum(['name', 'description', 'combined']),
  metadata: z
    .object({
      language: z.string().default('en'),
      modelVersion: z.string().default('text-embedding-3-small'),
    })
    .optional(),
});

export type ProductEmbedding = z.infer<typeof ProductEmbeddingSchema>;

/**
 * Vector search query parameters
 */
export interface VectorSearchQuery {
  vector: number[];
  topK?: number;
  filter?: string; // Milvus filter expression
  outputFields?: string[];
}

/**
 * Vector search result
 */
export interface VectorSearchResult {
  id: string;
  score: number;
  fields: Record<string, any>;
}

/**
 * Batch operation result
 */
export interface BatchOperationResult {
  success: boolean;
  inserted: number;
  failed: number;
  errors?: Array<{ index: number; error: string }>;
}

/**
 * Index type for vector fields
 */
export enum IndexType {
  IVF_FLAT = 'IVF_FLAT',
  IVF_SQ8 = 'IVF_SQ8',
  IVF_PQ = 'IVF_PQ',
  HNSW = 'HNSW',
  DISKANN = 'DISKANN',
}

/**
 * Metric type for similarity calculation
 */
export enum MetricType {
  L2 = 'L2', // Euclidean distance
  IP = 'IP', // Inner product
  COSINE = 'COSINE', // Cosine similarity
}

/**
 * Collection field schema
 */
export interface FieldSchema {
  name: string;
  description?: string;
  data_type: number; // Milvus DataType enum
  is_primary_key?: boolean;
  autoID?: boolean;
  dim?: number; // For vector fields
}

/**
 * Index parameters
 */
export interface IndexParams {
  index_type: IndexType;
  metric_type: MetricType;
  params: Record<string, any>;
}
